### PR TITLE
Update from master

### PR DESCRIPTION
**Pull request by pwildenhain**
So that redcap-tools/PyCap#77 can be merged

### CODE REVIEW

**Comment by baxpr** [comment]
@bud42 @KarthikMasi can you all review this?

**Comment by KarthikMasi** [comment]
"Adding in new delete functionality #77" isn't approved by the CI tool on REDCap master repo. Looks like it failed some test there.

**Comment by pwildenhain** [comment]
Yup, once this is merged, that test shouldn't fail anymore. 

This code is being tested against an older test suite, where the API was called directly. Now the tests have been refactored to work with mock `Response` objects, so that shouldn't be a problem after this is merged.

**Comment by baxpr** [comment]
Let's give it a go and see what happens! Thanks y'all

**Pull request merged**
